// Generated by CoffeeScript 1.4.0
(function() {
  var app, connected, express, fs, host, io, logFile, net, nscConnect, nscDisconnect, path, port, server;

  app = require('express')();

  express = require('express');

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  net = require('net');

  fs = require('fs');

  path = require('path');

  logFile = 'log/NSC_LOG.txt';

  host = 'localhost';

  port = 12345;

  connected = false;

  if (process.argv.length <= 2) {
    console.log('No server & port specified. The format is node server [\'ip\'] [\'port\'].  Connecting on localhost:12345');
  } else {
    host = process.argv[2];
    if (process.argv.length >= 4) {
      port = process.argv[3];
    }
  }

  nscConnect = (function() {
    console.log('Attempting to connect to NSC server ...');
    exports.client = net.connect(port, host, (function() {
      console.log('client connected');
      fs.writeFile(logFile, '');
      return connected = true;
    }));
    exports.client.on('error', (function() {
      console.log('error connecting to Neuro-Sand-Cube server.  Retrying...');
      return connected = false;
    }));
    exports.client.on('close', (function() {
      console.log('Connection closed.');
      connected = false;
      return nscConnect();
    }));
    exports.client.on('timeout', function() {
      return nscDisconnect();
    });
    return exports.client.on('end', function() {
      connected = false;
      return nscDisconnect();
    });
  });

  nscConnect();

  nscDisconnect = (function() {
    console.log('Disconnected from NSC server...');
    return nscConnect();
  });

  server.listen(8000);

  app.get('/', (function(req, res) {
    return res.sendfile(__dirname + '/index.html');
  }));

  app.get('/log', (function(req, res) {
    var file, filename, filestream;
    file = __dirname + logFile;
    filename = path.basename(file);
    res.attachment(filename);
    res.setHeader('Content-disposition', 'attachment; filename=' + filename);
    filestream = fs.createReadStream(file);
    filestream.on('data', function(chunk) {
      return res.write(chunk);
    });
    return filestream.on('end', function() {
      return res.end();
    });
  }));

  exports.client.on('data', (function(data) {
    return fs.appendFile(logFile, data.toString());
  }));

  io.sockets.on('connection', (function(socket) {
    exports.client.on('data', (function(data) {
      return socket.emit('nsc', data.toString());
    }));
    setInterval((function() {
      return socket.emit('connection', {
        "connected": connected
      });
    }), 5000);
    return socket.on('command', (function(data) {
      console.log(JSON.stringify(data));
      return exports.client.write(JSON.stringify(data));
    }));
  }));

}).call(this);
